language: php

php:
    - 5.6

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php artisan migrate --force
    - cp .env.travis .env
    - php artisan key:generate

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml

services:
    - mysql

env:
  global:
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=jobboard
    - DB_USERNAME=root
    - DB_PASSWORD=

before_install:
    - mysql -e "create database IF NOT EXISTS jobboard;" -uroot

after_success:
    - bash <(curl -s https://codecov.io/bash)